# Copyright (c) Facebook, Inc. and its affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

version: 2.1

# TODO: fix all this up once CircleCI is enabled
commands:
  test:
    steps:
      - run:
          name: "Build from Source"
          command: |
            if [ ! -z "$DOCKER_USERNAME" ]
            then
                sudo docker login -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD
            fi

workflows:
  version: 2
  test_and_install:
    jobs:
      - test
  
